version: 2
jobs:
    build:
        docker:
            - image: node:10-browsers
        steps:
            - checkout
            - run: npm run install
            - run: npm run dev

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
                branches:
                    - develop
                    - initialSetupCircleCI
